www/bajir/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :procedures

  resources :surveyresponses

  resources :answers

  resources :surveytemplates do
    resources :questions
  end

  resources :operations

  root 'welcome#index'

end

www/bajir/app/models/answer.rb
class Answer < ActiveRecord::Base
    belongs_to :question
end

www/bajir/app/models/operation.rb
class Operation < ActiveRecord::Base
    has_many :procedures
    has_many :surveytemplates
    
    #unsure whether both of these validations work in this format
    validates :code, presence: true
    validates :description, presence: true
end

www/bajir/app/models/procedure.rb
class Procedure < ActiveRecord::Base
	belongs_to :operation
    has_many :surveyresponses
    validates :tnumber, presence: true,
					length: { minimum: 1 }
end

www/bajir/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :surveytemplate
  has_many :answers
end

www/bajir/app/models/surveyresponse.rb
class Surveyresponse < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :surveytemplate
end

www/bajir/app/models/surveytemplate.rb
class Surveytemplate < ActiveRecord::Base
	has_and_belongs_to_many :operations
    has_many :questions, dependent: :destroy
    has_many :surveyresponses
end

www/bajir/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

www/bajir/app/controllers/javascripts_controller.rb
class JavascriptsController < ApplicationController
    def dynamic_procedures
        @procedure = Procedure.find(:all)
    end
end

www/bajir/app/controllers/operations_controller.rb
class OperationsController < ApplicationController

    def index
        @operations = Operation.all
    end

    def show
        @operation = Operation.find(params[:id])
    end

    def new
        @operation = Operation.new
    end

    def edit
        @operation = Operation.find(params[:id])
    end

    def create
        @operation = Operation.create(operation_params)
        if @operation.save
            redirect_to operations_path
        else
            render 'new'
        end
    end

    def update
        @operation = Operation.find(params[:id])

        if @operation.update(operation_params)
            redirect_to operations_path
        else
            render 'edit'
        end
    end

    def destroy
        @operation = Operation.find(params[:id])
        @operation.destroy

        redirect_to operations_path
    end

private
    def operation_params
        params.require(:operation).permit(:code, :description)
    end

end

www/bajir/app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController

	def index
    	@procedures = Procedure.all
  	end

	def show
    	@procedure = Procedure.find(params[:id])
  	end

    def new
    	@procedure = Procedure.new
      @operations = Operation.all
    end

	def edit
  		@procedure = Procedure.find(params[:id])
      @operations = Operation.all
	end

  def create
  	@procedure = Procedure.new(procedure_params)
  	if @procedure.save
  		redirect_to procedures_path
  	else
  		render 'new'
  	end
  end

  def update
		@procedure = Procedure.find(params[:id])

		if @procedure.update(procedure_params)
  		redirect_to procedures_path
		else
  		render 'edit'
		end
	end

	def destroy
  		@procedure = Procedure.find(params[:id])
  		@procedure.destroy

  		redirect_to procedures_path
	end

private
	def procedure_params
		params.require(:procedure).permit(:tnumber, :procedureDate)
	end

end

www/bajir/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def create
		@surveytemplate = Surveytemplate.find(params[:surveytemplate_id])
		@question = @surveytemplate.questions.create(question_params)
		redirect_to edit_surveytemplate_path(@surveytemplate)
	end

  def destroy
    @surveytemplate = Surveytemplate.find(params[:surveytemplate_id])
    @question = @surveytemplate.questions.find(params[:id])
    @question.destroy
    redirect_to surveytemplate_path(@surveytemplate)
  end

	private
	def question_params
		params.require(:question).permit(:question, :answerParameters)

	end
end

www/bajir/app/controllers/surveyresponses_controller.rb
class SurveyresponsesController < ApplicationController
	def new
		@surveyresponse = Surveyresponse.new
	end

	def edit
  		@surveyresponse = @procedure.surveyresponses.find(params[:id])

	end

	def create
		@surveyresponse = Surveyresponse.new(surveyresponse_params)
		if @surveyresponse.save
            render 'edit'
        else
            render 'new'
        end
	end

	def destroy
    @surveyresponse = @procedure.surveyresponses.find(params[:id])
    @surveyresponse.destroy
    redirect_to surveyresponse_path(@surveyresponse)
  end

	private
		def surveyresponse_params
<<<<<<< Updated upstream
		params.require(:surveyresponse).permit(:procedure_id, :date, :surveytemplate_id)
||||||| merged common ancestors
		params.require(:surveyresponse).permit(:date, :survey)
=======
		params.require(:surveyresponse).permit(:survey, :date)
>>>>>>> Stashed changes
	end
end

www/bajir/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

www/bajir/app/helpers/application_helper.rb
module ApplicationHelper
    def javascript(*files)
      content_for(:head) { javascript_include_tag(*files) }
    end
end

www/bajir/app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

www/bajir/app/helpers/operations_helper.rb
module OperationsHelper
end

www/bajir/app/helpers/procedures_helper.rb
module ProceduresHelper
end

www/bajir/app/helpers/question_helper.rb
module QuestionHelper
end

www/bajir/app/helpers/questions_helper.rb
module QuestionsHelper
end

www/bajir/app/helpers/surveyresponses_helper.rb
module SurveyresponsesHelper
end

www/bajir/app/helpers/surveytemplates_helper.rb
module SurveytemplatesHelper
end

www/bajir/app/helpers/welcome_helper.rb
module WelcomeHelper
end

www/bajir/app/views/javascripts/dynamic_procedures.js.erb
var procedures = new Array();
<% for procedure in @procedures -%>
  procedures.push(new Array(<%= procedure.tnumber %>, '<%=h procedure.operation_id %>', <%= procedure.id %>));
<% end -%>

function patientSelected() {
  tnumber = $('person_country_id').getValue();
  options = $('person_procedure_id').options;
  options.length = 1;
  procedures.each(function(procedure) {
    if (procedure[0] == country_id) {
      options[options.length] = new Option(procedure[1], procedure[2]);
    }
  });
  if (options.length == 1) {
    $('procedure_field').hide();
  } else {
    $('procedure_field').show();
  }
}

document.observe('dom:loaded', function() {
  countrySelected();
  $('person_country_id').observe('change', countrySelected);
});

www/bajir/app/views/surveyresponses/_formedit.html.erb
<%= form_for @surveyresponse do |f| %>
  <p>
    <%= f.label :date_of_completion %><br>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :type_of_questionnaire %><br>
    <%= f.text_field :survey %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>])

www/bajir/app/views/surveyresponses/_simpleform.html.erb
<%= simple_form_for @surveyresponse  do |f| %>

    <%= f.label 'Patient ID' %><br />
    <%= f.select 'id', options_for_select(Procedure.uniq.pluck(:tnumber)) {|p| [p.tnumber, p.tnumber]}, {include_blank: true, default: nil}, {:class => 'select optional form-control'} %>

    <%= f.association :procedure, label: 'Patient ID', prompt: 'Select the patient T-number' %>

    <%= f.association :surveytemplate, :value_method => :id, label: 'Type of questionnaire', prompt: 'Select the questionnaire' %>

    <%= f.input :date, :as => :date_picker, label: 'Completion Date' %>

    <%= f.button :submit , label: 'Continue' %>

<% end %>

www/bajir/app/views/surveyresponses/_surveyresponse.html.erb
	<tr>
		<td><%= surveyresponse.surveytemplate.name %></td>
		<td><%= surveyresponse.date %></td>
		<td><%= link_to 'Delete', [surveyresponse.procedure, surveyresponse],
				method: :delete,
				data: { confirm: 'Are you sure?' } %></td>
	</tr>

www/bajir/app/views/surveyresponses/edit.html.erb
<h1>Editing Questionnaire Response</h1>

<%= render 'simpleform' %>


<%= render 'formedit' %>

<%= link_to 'Back', procedure_path(@procedure) %>

www/bajir/app/views/surveyresponses/new.html.erb
<h1>New Questionnaire Response</h1>
<% javascript 'dynamic_procedures' %>

<%= render 'simpleform' %>

<%= link_to 'Back', surveyresponses_path %>

www/bajir/app/views/welcome/index.html.erb
<h1>BAJIR</h1>
<p>Welcome to the BAJIR homepage</p>
<div>
	<%= link_to 'New Procedure', new_procedure_path %>
	<%= link_to 'All Procedures', controller: 'procedures' %>
</div>
<div>
	<%= link_to 'Create Questionnaire Template', new_surveytemplate_path %>
	<%= link_to 'All Questionnaires Templates', controller: 'surveytemplates' %>
</div>
<div>
	<%= link_to 'Create Operation', new_operation_path %>
	<%= link_to 'All Operations', controller: 'operations' %>
</div>
<div>
    <%= link_to 'Add Questionnaire Response', new_surveyresponse_path %>
    <%= link_to 'All Questionnaire Response', controller: 'surveyresponses' %>
</div>