www/bajir/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :procedures

  resources :surveyresponses

  resources :answers

  resources :surveytemplates do
    resources :questions
  end

  resources :operations

  root 'welcome#index'

end

www/bajir/app/models/answer.rb
class Answer < ActiveRecord::Base
    belongs_to :question
end

www/bajir/app/models/operation.rb
class Operation < ActiveRecord::Base
    has_many :procedures
    has_many :surveytemplates
    
    #unsure whether both of these validations work in this format
    validates :code, presence: true
    validates :description, presence: true
end

www/bajir/app/models/procedure.rb
class Procedure < ActiveRecord::Base
	belongs_to :operation
    has_many :surveyresponses
    validates :tnumber, presence: true,
					length: { minimum: 1 }
end

www/bajir/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :surveytemplate
  has_many :answers
end

www/bajir/app/models/surveyresponse.rb
class Surveyresponse < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :surveytemplate
end

www/bajir/app/models/surveytemplate.rb
class Surveytemplate < ActiveRecord::Base
	has_and_belongs_to_many :operations
    has_many :questions, dependent: :destroy
    has_many :surveyresponses
end

www/bajir/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

www/bajir/app/controllers/javascripts_controller.rb
class JavascriptsController < ApplicationController
    def dynamic_procedures
        @procedure = Procedure.find(:all)
    end
end

www/bajir/app/controllers/operations_controller.rb
class OperationsController < ApplicationController

    def index
        @operations = Operation.all
    end

    def show
        @operation = Operation.find(params[:id])
    end

    def new
        @operation = Operation.new
    end

    def edit
        @operation = Operation.find(params[:id])
    end

    def create
        @operation = Operation.create(operation_params)
        if @operation.save
            redirect_to operations_path
        else
            render 'new'
        end
    end

    def update
        @operation = Operation.find(params[:id])

        if @operation.update(operation_params)
            redirect_to operations_path
        else
            render 'edit'
        end
    end

    def destroy
        @operation = Operation.find(params[:id])
        @operation.destroy

        redirect_to operations_path
    end

private
    def operation_params
        params.require(:operation).permit(:code, :description)
    end

end

www/bajir/app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController

	def index
    	@procedures = Procedure.all
  	end

	def show
    	@procedure = Procedure.find(params[:id])
  	end

    def new
    	@procedure = Procedure.new
      @operations = Operation.all
    end

	def edit
  		@procedure = Procedure.find(params[:id])
      @operations = Operation.all
	end

  def create
  	@procedure = Procedure.new(procedure_params)
  	if @procedure.save
  		redirect_to procedures_path
  	else
  		render 'new'
  	end
  end

  def update
		@procedure = Procedure.find(params[:id])

		if @procedure.update(procedure_params)
  		redirect_to procedures_path
		else
  		render 'edit'
		end
	end

	def destroy
  		@procedure = Procedure.find(params[:id])
  		@procedure.destroy

  		redirect_to procedures_path
	end

private
	def procedure_params
		params.require(:procedure).permit(:tnumber, :procedureDate)
	end

end

www/bajir/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def create
		@surveytemplate = Surveytemplate.find(params[:surveytemplate_id])
		@question = @surveytemplate.questions.create(question_params)
		redirect_to edit_surveytemplate_path(@surveytemplate)
	end

  def destroy
    @surveytemplate = Surveytemplate.find(params[:surveytemplate_id])
    @question = @surveytemplate.questions.find(params[:id])
    @question.destroy
    redirect_to surveytemplate_path(@surveytemplate)
  end

	private
	def question_params
		params.require(:question).permit(:question, :answerParameters)

	end
end

www/bajir/app/controllers/surveyresponses_controller.rb
class SurveyresponsesController < ApplicationController
	def new
		@surveyresponse = Surveyresponse.new
	end

	def edit
  		@surveyresponse = @procedure.surveyresponses.find(params[:id])

	end

	def create
		@surveyresponse = Surveyresponse.new(surveyresponse_params)
		if @surveyresponse.save
            render 'edit'
        else
            render 'new'
        end
	end

	def destroy
    @surveyresponse = @procedure.surveyresponses.find(params[:id])
    @surveyresponse.destroy
    redirect_to surveyresponse_path(@surveyresponse)
  end

	private
		def surveyresponse_params
<<<<<<< Updated upstream
		params.require(:surveyresponse).permit(:procedure_id, :date, :surveytemplate_id)
||||||| merged common ancestors
		params.require(:surveyresponse).permit(:date, :survey)
=======
		params.require(:surveyresponse).permit(:survey, :date)
>>>>>>> Stashed changes
	end
end

www/bajir/app/controllers/surveytemplates_controller.rb
class SurveytemplatesController < ApplicationController
    def index
        @surveytemplates = Surveytemplate.all
    end

    def show
        @surveytemplate = Surveytemplate.find(params[:id])
    end

    def new
        @surveytemplate = Surveytemplate.new
    end

    def edit
        @surveytemplate = Surveytemplate.find(params[:id])
    end

    def create
        @surveytemplate = Surveytemplate.new(surveytemplate_params)
        if @surveytemplate.save
            render 'edit'
        else
            render 'new'
        end
    end

    def update
        @surveytemplate = Surveytemplate.find(params[:id])

        if @surveytemplate.update(surveytemplate_params)
            redirect_to @surveytemplate
        else
            render 'edit'
        end
    end

    def destroy
        @surveytemplate = Surveytemplate.find(params[:id])
        @surveytemplate.destroy

        redirect_to surveytemplates_path
    end

private
    def surveytemplate_params
        params.require(:surveytemplate).permit(:name, :description)
    end

end

www/bajir/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

www/bajir/app/helpers/application_helper.rb
module ApplicationHelper
    def javascript(*files)
      content_for(:head) { javascript_include_tag(*files) }
    end
end

www/bajir/app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

www/bajir/app/helpers/operations_helper.rb
module OperationsHelper
end

www/bajir/app/helpers/procedures_helper.rb
module ProceduresHelper
end

www/bajir/app/helpers/question_helper.rb
module QuestionHelper
end

www/bajir/app/helpers/questions_helper.rb
module QuestionsHelper
end

www/bajir/app/helpers/surveyresponses_helper.rb
module SurveyresponsesHelper
end

www/bajir/app/helpers/surveytemplates_helper.rb
module SurveytemplatesHelper
end

www/bajir/app/helpers/welcome_helper.rb
module WelcomeHelper
end

www/bajir/app/views/operations/_form.html.erb
<%= simple_form_for @operation do |f| %>

  <%= f.input :code, label: 'Operation Code', error: 'Operation Code is manatory, please specify one' %><br>
  <%= f.input :description, label: 'Description of the operation' %>
  <%= f.submit %>

<% end %>

www/bajir/app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

www/bajir/app/views/operations/index.html.erb
<h1>Listing operations</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>

  <% @operations.each do |operation| %>
    <tr>
      <td><%= operation.code %></td>
      <td><%= operation.description %></td>
      <td><%= link_to 'Show', operation_path(operation) %></td>
      <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
      <td><%= link_to 'Destroy', operation_path(operation),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

www/bajir/app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

www/bajir/app/views/operations/show.html.erb
<p>
  <strong>Code:</strong>
  <%= @operation.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @operation.description %>
</p>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operation_path %>

www/bajir/app/views/procedures/_form.html.erb
<%= simple_form_for @procedure do |f| %>
 
  <%= f.input :tnumber, label: 'Unique Trust Number', required: true, error: 'Trust number is mandatory, please specify one' %>
   <%= f.input :procedureDate, as: :date_picker, label: 'Date',  required: true, error: 'Date is mandatory, please specify one',input_html: {data: {date_options: {
                        defaultDate: '2012/12/25',
                        showClose: true
                }}} %>
  <%= f.button :submit %>
 
<% end %>

www/bajir/app/views/procedures/_simpleform.html.erb
<%= simple_form_for @procedure do |f| %>
 
	<%= f.input :tnumber, label: 'Unique Trust Number', required: true, error: 'Trust number is mandatory, please specify one' %>
   	<%= f.input :procedureDate, :as => :date_picker, label: 'Date',  required: true, error: 'Date is mandatory, please specify one'%>
  	<%= f.collection_select :operation_id, Operation.all, :id, :code, {:prompt => 'Please select the type of operation'} %> 
  	<%= f.button :submit %>
 
<% end %>								

www/bajir/app/views/procedures/edit.html.erb
<h1>Editing procedure</h1>

<%= render 'simpleform' %>

<%= link_to 'Back', procedures_path %>

www/bajir/app/views/procedures/index.html.erb
<h1>Listing procedures</h1>
 
<table>
  <tr>
    <th>T Number</th>
    <th>Operation Date</th>
    <th>Operation Code</th>
    <th colspan="2"></th>
  </tr>
 
  <% @procedures.each do |procedure| %>
    <tr>
      <td><%= procedure.tnumber %></td>
      <td><%= procedure.procedureDate %></td>
      <td><%= procedure.operation_id %></td>
      
      <td><%= link_to 'Show', procedure_path(procedure) %></td>
      <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
      <td><%= link_to 'Destroy', procedure_path(procedure),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

www/bajir/app/views/procedures/new.html.erb
<h1>New Procedure</h1>

<%= render 'simpleform' %>

<%= link_to 'Back', procedures_path %>

www/bajir/app/views/procedures/show.html.erb
<h2>Procedure Details</h2>
<p>
  <strong>T Number:</strong>
  <%= @procedure.tnumber %>
</p>

<p>
  <strong>Procedure Date:</strong>
  <%= @procedure.procedureDate %>
</p>

<p>
  <strong>Operation</strong>
  <%= @procedure.operation_id %> [Need to change this to reflect operation code and description]
</p>

<%= link_to 'Edit', edit_procedure_path(@procedure) %> |
<%= link_to 'Back', procedures_path %>

<h3>Completed questionnaires</h3>
<table>
	<tr>
		<th>Questionnaire</th>
		<th>Date of Completion</th>
		<th colspan="2"></th>
	</tr>
<%= render @procedure.surveyresponses %>
</table>

<h2>Add a Questionnaire:</h2>
<%= render 'surveyresponses/form' %>

www/bajir/app/views/questions/_form.html.erb
<%= form_for([@surveytemplate, @surveytemplate.questions.build]) do |f| %>
  <p>
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.label :answerParameters %><br>
    <%= f.text_area :answerParameters %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

www/bajir/app/views/questions/_question.html.erb
<p>
  <strong>Question:</strong>
  <%= question.question %>
</p>
 
<p>
  <strong>answerParameters:</strong>
  <%= question.answerParameters %>
</p>

<p>
	<%= link_to 'Delete Question', [question.surveytemplate, question],
           method: :delete,
           data: { confirm: 'Are you sure?' } %>
</p>

www/bajir/app/views/surveytemplates/_form.html.erb
<%= form_for @surveytemplate do |f| %>

  <% if @surveytemplate.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@surveytemplate.errors.count, "error") %> prohibited
        this procedure from being saved:
      </h2>
      <ul>
        <% @surveytemplate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

www/bajir/app/views/surveytemplates/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render 'form' %>

<%= render @surveytemplate.questions %>

<%= render 'questions/form' %>

<%= link_to 'Back', surveytemplates_path %>

www/bajir/app/views/surveytemplates/index.html.erb
<h1>Listing questionnaires</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>

  <% @surveytemplates.each do |surveytemplate| %>
    <tr>
      <td><%= surveytemplate.name %></td>
      <td><%= surveytemplate.description %></td>
      <td><%= link_to 'Show', surveytemplate_path(surveytemplate) %></td>
      <td><%= link_to 'Edit', edit_surveytemplate_path(surveytemplate) %></td>
      <td><%= link_to 'Destroy', surveytemplate_path(surveytemplate),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

www/bajir/app/views/surveytemplates/new.html.erb
<h1>New Questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Back', surveytemplates_path %>

www/bajir/app/views/surveytemplates/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @surveytemplate.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @surveytemplate.description %>
</p>

<%= link_to 'Edit', edit_surveytemplate_path(@surveytemplate) %> |
<%= link_to 'Back', surveytemplates_path %>

<%= render @surveytemplate.questions %>